#!/bin/sh
# What is this script?
# This is a script for building cross-target GNU GDB tools targeting Risc-V archs.
#
# Requirements: 
# flex bison libgmp3-dev libmpfr-dev autoconf texinfo build-essential libncurses5-dev
#
# How to run
# Just type './build_riscv_gdb' in your favorite terminal. DO NOT run as root.
gdb_base="gdb-8.3.1"

root_dir=`pwd`

TARGET=riscv32-unknown-elf
PREFIX=${root_dir}/$TARGET/${gcc_base}
BUILD=i686-linux-gnu

# setup our toolchain new path
export PATH=$PREFIX/bin:$PATH

dl_dir="${root_dir}/download"
src_dir="${root_dir}/source"
bld_dir="${root_dir}/build"
install_dir="${root_dir}/install"

mkdir $src_dir
mkdir $bld_dir
mkdir $install_dir
mkdir $dl_dir

# download all sources
cd $dl_dir
wget -c ftp://ftp.gnu.org/gnu/gdb/${gdb_base}.tar.gz

# unpack everything
cd $src_dir
tar xvzf ${dl_dir}/"${gdb_base}.tar.gz"

cd $bld_dir
mkdir ${gdb_base}
cd ${gdb_base}
${src_dir}/${gdb_base}/configure --target=$TARGET --prefix=$PREFIX \
    --disable-shared --disable-threads --enable-tls --enable-languages=c,c++ \
    --with-newlib --disable-libmudflap --disable-libssp --disable-libquadmath \
    --disable-libgcmp --disable-nls --disable-multilibs

make all-gdb
make install-gdb

