name: C++ build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make (single-core-ext)
      working-directory: cd platforms/single-core-ext
      run: make
